#          - hostname: "*.{{ .Values.global.domain }}"
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-cloudflared-tunnel
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.cloudflared_tunnel.namespace }}
  source:
    chart: cloudflared
    repoURL: https://khuedoan.github.io/charts
    targetRevision: 0.3.3
    helm:
      releaseName: cloudflared
      values: |
        credentials:
          existingSecret: cloudflared-credentials
        config:
          tunnel: humble-tunnel
          ingress:
          - hostname: "*.475962.xyz"
            service: http://system-ingress-nginx-controller.ingress-nginx:80
            originRequest:
              noTLSVerify: true
          - service: http_status:404
        podMonitor:
          enabled: true
          metricsEndpoints:
            - port: http
