---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: jellyfin-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---