{{- if .Values.kratos.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-kratos
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.argocd.project }}
  source:
    chart: kratos
    repoURL: https://k8s.ory.sh/helm/charts
    targetRevision: 0.23.3
    helm:
      releaseName: kratos
      values: |
        kratos:
            config:  
                identity:            
                    schemas:
                        - id: customer
                          url: base64://ewogICIkc2NoZW1hIjogImh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDcvc2NoZW1hIyIsCiAgInR5cGUiOiAib2JqZWN0IiwKICAicHJvcGVydGllcyI6IHsKICAgICJiYXIiOiB7CiAgICAgICJ0eXBlIjogInN0cmluZyIKICAgIH0KICB9LAogICJyZXF1aXJlZCI6IFsKICAgICJiYXIiCiAgXQp9
                selfservice:
                    default_browser_return_url: https://my-app.com/dashboard
                courier:
                    connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false
                dsn: postgres://postgres:postgres@default.acid-test-0:5432/db
{{- end }}
