{{- if .Values.jellyfin.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelab/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: jellyfin-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
{{- end }}
{{- if .Values.radarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-media-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelab/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: radarr-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
{{- end }}
{{- if .Values.sonarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-media-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelab/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: sonarr-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
{{- end }}
{{- if .Values.bazarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-media-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelab/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-media-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: bazarr-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
---
{{- end }}
{{- if .Values.qbittorent.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-media-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelab/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-media-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: qbittorrent-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelab/downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: qbittorrent-downloads-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
---
{{- end }}
