{{- if .Values.jellyfin.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/config/jellyfin"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: jellyfin-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: jellyfin-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
{{- end }}
{{- if .Values.radarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/config/radarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: radarr-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-media-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: radarr-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
{{- end }}
{{- if .Values.sonarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/config/sonarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: sonarr-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-media-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: sonarr-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
{{- end }}
{{- if .Values.bazarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-config-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/config/bazarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: bazarr-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-media-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-media-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: bazarr-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
{{- end }}
{{- if .Values.qbittorrent.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/config/qbittorrent"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: qbittorrent-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-media-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-media-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: qbittorrent-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: qbittorrent-downloads-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
---
{{- end }}
{{- if .Values.prowlarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
  namespace: apps
spec:
  storageClassName: manual
  capacity:
    storage: {{.Values.mediastorage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/homelabnfs/config/prowlarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
  namespace: apps
spec:
  storageClassName: manual
  volumeName: prowlarr-config-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mediastorage.size }}
{{- end }}
