apiVersion: v1
appVersion: "1.0"
description: Bootstrap the platform layer
name: platform
version: 0.2.0

dependencies:
  - name: common
    version: 1.16.0
    repository: https://charts.bitnami.com/bitnami
  - name: common
    version: 4.4.2
    repository: https://k8s-at-home.com/charts/
