# Default
argocd:
  project: system
  namespace: argocd

global:
  domain: "placeholder.com"

# Storage
longhorn:
  enabled: false
  namespace: longhorn-system

# Observability
monitoring:
  enabled: true
  namespace: observability

tracing:
  enabled: false
  namespace: observability

logging:
  enabled: false
  namespace: observability

dashboard:
  enabled: false
  namespace: observability
  targetRevision: main

opentelemetry:
  enabled: false
  namespace: observability
  logLevel: info

# Ingress / Load balancer
metallb:
  enabled: true
  namespace: metallb-system

ingress_nginx:
  enabled: true

certmanager:
  enabled: false
  namespace: cert-manager

istio:
  enabled: false
  namespace: istio-system
  gateway:
    enabled: false

# System maintainers/cleaners
descheduler:
  enabled: false
  namespace: descheduler

systemUpgrade:
  enabled: false

kured:
  enabled: false

#backup
k8up:
  enabled: true
  namespace: k8up
