{{- if .Values.jellyfin.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-jellyfin
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argocd.project }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: {{ .Values.jellyfin.namespace }}
  source:
    chart: k8s-at-home/jellyfin
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 11.5.1
    helm:
      releaseName: jellyfin
      values: |
        persistence:
            media:
                enabled: true
                mountPath: /media

{{- end }}
