argocd:
  namespace: argocd
  project: apps
  targetRevision: main

global:
  domain: "placeholder.com"

filebrowser:
  enabled: false

dendrite:
  enabled: true

element:
  enabled: true

# Playground services
memcached:
  enabled: false

cortex:
  enabled: false
  basicAuth:
    insecure: true
    secretName: "cortex-humble-tenant"

microservicesDemo:
  enabled: false

dashyLandscape:
  enabled: true

consul:
  enabled: false

nfs:
  enabled: false

yutaops:
  enabled: true

# netflix
mediastorage:
  size: "5Gi"
jellyfin:
  enabled: true
radarr:
  enabled: true
sonarr:
  enabled: true
prowlarr:
  enabled: true
bazarr:
  enabled: true
qbittorrent:
  enabled: true
